# Generated by Django 3.1.6 on 2022-04-17 22:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(99999999), django.core.validators.MinValueValidator(10000000)])),
                ('date_exp', models.DateField()),
                ('brand', models.CharField(max_length=255)),
            ],
        ),
    ]
